### PR TITLE
chore: catalog improvements

### PR DESCRIPTION
**Pull request by sk-**
- Simplified the summary so that it looks good on our documentation sites
- Removed spanish words
- Added tags for the Health Ceheck endpoint

### CODE REVIEW

**Comment by sk-** [comment]
@fcifuentesq @twolfvb la parte de la paginacion esta super confusa.

Hay varias cosas que no entiendo que hacen la implementacion mas confusa.
1. Por que la API tiene que entregar un prev y un next?
2. Por que la API recibe un prev y un next? Que significan? Generalmente las api paginadas reciben un `pageToken`. De esa manera uno se puede mover hacia adelante o atras.

**Comment by sk-** [comment]
Other weird things I found about the definitions:

- Maximum page size is 51: why this odd number? Why not 50?
- Minimum page size is 1, but it should be 0.
- Why cant' ids have spaces?

**Comment by twolfvb** [comment]
I was just working with @jasanchez1 this morning and we had the same doubts.
> There are a couple of things I don't get about how pagination is implemented.
> 
> 1. Why does the API need to return both a `prev` and `next`?
The API doesn't NEED to return prev and next as far as I know.

> 2. Why does the API accept both and `prev` and `next`? What do they mean? Typically, paginated APIs receive a `pageToken`, which allow to move in either direction.

According to the docs, they both should behave the same, akin to a curr, pageId, or what you just described as pageToken
I feel like moving forward with pageToken is the way, I would take the other 2 out from the docs but leave them working until we know we can ask our current customers to use pageToken instead.

**Review by twolfvb — APPROVED** [review]
All changes look fine to me. 
We should probably document the questions in conversation or answer them there before closing

**Comment by twolfvb** [comment]
> Maximum page size is 51: why this odd number? Why not 50?
> Minimum page size is 1, but it should be 0.

Agree on both, can we change it to 0 and 50?
> Why cant' ids have spaces?

id's can't have spaces because it makes it more difficult (for us) to search by id

**Comment by PabloReszczynski** [comment]
When there is no next page, the `next` property should be omitted or be `null`. Same with `prev`.
The maximun items should be 50. Enumerated from 1 to 51.
The minimun items should be 0, with no `next` page

**Comment by sk-** [comment]
@PabloReszczynski and what do `next` and `prev` mean in the query params?

Do we even use the `prev` token? If not we should remove it to simplify the Catalog API implementation.

> When there is no next page, the `next` property should be omitted or be `null`. Same with `prev`. The maximun items should be 50. Enumerated from 1 to 51. The minimun items should be 0, with no `next` page

If there are 50 items maximum, how can they be enumerated from 1 to 51? Unfortunately, to change the value to 50, we would need to be sure that all Marketplaces which have implemented the API have not reached that limit.

**Comment by twolfvb** [comment]
> If there are 50 items maximum, how can they be enumerated from 1 to 51? Unfortunately, to change the value to 50, we would need to be sure that all Marketplaces which have implemented the API have not reached that limit.

Just tested this on the JOKR API, they are indeed sending 51.
@jasanchez1 just tested on ATIDA, they are sending 50.

**Comment by PabloReszczynski** [comment]
@sk- 
`next` and `prev` are pagination cursors. When the API responds with a `next`, we use that same key to get the next page in the following query.
The `prev` cursor is needed to go back to a previous page. We haven't implemented a use for it yet, but it doesn't mean we should get rid of it.

I'm all for increasing the limit. Since 50 is just a number we came with almost randomly

**Comment by sk-** [comment]
@PabloReszczynski and the query params? The idea is that the result of `next` is used in the `next` param, and the result of 
 `prev` in the `prev` param?

**Comment by PabloReszczynski** [comment]
@sk- For example, we can retrieve the first page like this:
`GET /categories/ -> { next: "asdf", response: [...] }`
If we can to get the next page, we do:
`GET /categories/?next=asdf -> { next" ghjk", response: [...] }`

**Pull request merged**
