### PR TITLE
chore: use consistent yml extensions

### PR DESCRIPTION
**Pull request by sk-**

### CODE REVIEW

**Comment by sk-** [comment]
@fcifuentesq this has a conflict with some Redocly validation

**Comment by sk-** [comment]
@twolfvb I got access but I cannot change the name of the file until the file is present on Github.

**Comment by twolfvb** [comment]
Just got access to redocly via Pancho.
I still cant access any of the redocly details. the passing bundle one says `File not found or you don't have access to it.`
The other 2 give a 404

**Comment by sk-** [comment]
> Just got access to redocly via Pancho. I still cant access any of the redocly details. the passing bundle one says `File not found or you don't have access to it.` The other 2 give a 404

I made you an owner. Let me see if you can see the results now.

In any case it's failing because the Api is configured to check the file with `.yaml` extension, and given that it does not exist it fails. Unfortunately I cannot change the check before the file exists in the repo.
Screen Shot 2022-01-13 at 9 53 27 AM

**Comment by twolfvb** [comment]
as an Owner I can see the results now, looks fine

**Review by twolfvb — APPROVED** [review]

**Pull request merged**
